### ISSUE TITLE
Google Workspace Accounts are not detected

### ISSUE THREAD

**Issue by iMonZ** [thunderbird/ews-rs#20]
Like I said in the Title. 
Google Workspace accounts support Exchange Clients out of the Box using Active Sync.
But sadly it doesn't detect my GW Accounts in the ews-rs latest Thunderbird Preview.

**Comment by leftmostcat** [comment]
This repository, while it forms the basis of support in Thunderbird, is not specific to Thunderbird, and issues with Thunderbird support should be directed to Bugzilla (https://bugzilla.mozilla.org/). That said, Thunderbird support is targeting the Exchange Web Services protocol, and Exchange Active Sync is a separate protocol for which support is not planned.
